# Generated by Django 5.0.6 on 2024-05-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('describe', models.TextField(max_length=500)),
                ('created', models.DateTimeField(null=True)),
                ('datecompleted', models.DateTimeField(null=True)),
            ],
        ),
    ]
