# Generated by Django 5.0.6 on 2024-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_user_alter_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendente'), ('InProgress', 'Em andamento'), ('Completed', 'Concluído'), ('Delayed', 'Atrasado')], default='Pending', max_length=20),
        ),
    ]
